# Generated by Django 4.2.18 on 2025-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="accounts.userinterest"),
        ),
    ]
